In [3]:
import pandas as pd
import os #Files in listen abgreifen
import re # Regex brauchen wir, um die Namen aus den Filenamen rauszugreifen

In [4]:
file_namen = os.listdir('Lieferung_SEB-Schulergebnisse_2/Schulberichte/Tabellen_2015')
jahr = 2015
dic_list = []

In [5]:
for file in file_namen:
    regex = r".*\b(?= Anhang)"
    name = re.search(regex, file, re.IGNORECASE).group()
    if "Gym" in name:
        regex = r".*\b(?= Gym.*)"
        name = re.search(regex, name, re.IGNORECASE).group()
    if "KS" in name:
        regex = r"(?<=KS ).*\b"
        name = re.search(regex, name, re.IGNORECASE).group()

    # Jetzt öffnen wir das jeweilige File als Dataframe:
    
    df = pd.read_excel("Lieferung_SEB-Schulergebnisse_2/Schulberichte/Tabellen_2015/" + str(file))
    
    zufr = df.loc[20,"Unnamed: 3"]
    vorb_f = df.loc[22,"Unnamed: 3"]
    vorb_p = df.loc[24,"Unnamed: 3"]
    prob = df.loc[56,"Unnamed: 3"]
    urt = df.loc[58,"Unnamed: 3"]
    zus = df.loc[60,"Unnamed: 3"]
    konf = df.loc[62,"Unnamed: 3"]

    mini_dict = {"jahr": jahr, 
                 "name": name, 
                 "zufr": zufr, 
                 "vorb_f": vorb_f, 
                 "vorb_p":vorb_p, 
                 "prob": prob, 
                 "urt": urt, 
                 "zus": zus, 
                 "konf": konf}
    dic_list.append(mini_dict)

In [6]:
df_final = pd.DataFrame(dic_list)
df_final.to_csv("Pandas_Results2015.csv")
df_final

,jahr,name,zufr,vorb_f,vorb_p,prob,urt,zus,konf
0,2015,Buelrain,4.9,4.2,4.3,4.2,4.2,4.6,4.0
1,2015,KME,4.9,4.0,4.4,4.1,4.3,4.3,3.7
2,2015,MNG Raemibuehl,4.5,4.6,3.7,3.8,3.8,4.1,3.6
3,2015,Hohe Promenade,5.0,4.4,4.8,4.6,4.5,4.8,4.1
4,2015,Zuercher Unterland,5.2,4.5,4.4,4.4,4.6,4.6,4.2
5,2015,Freudenberg,5.2,4.3,4.7,4.8,4.7,5.0,4.3
6,2015,KZO,4.9,4.3,4.5,4.3,4.4,4.8,4.0
7,2015,Realgymnasium Raemibuehl,5.1,4.1,4.9,4.6,4.9,5.0,4.7
8,2015,Liceo Artistico,5.0,4.0,5.1,4.9,5.3,5.3,4.7
9,2015,Hottingen,4.6,3.9,4.4,4.0,4.4,4.5,4.0
10,2015,Literaturgymnasium Raemibuehl,5.0,4.0,4.6,4.4,4.1,4.7,3.8
11,2015,Wiedikon,4.7,4.1,4.1,4.0,3.8,4.8,3.8
12,2015,Nord,4.8,4.1,4.3,4.1,4.2,4.9,4.0
13,2015,Rychenberg,4.8,4.3,4.2,4.3,3.9,4.4,3.6
14,2015,Limmattal,4.8,4.5,4.2,4.3,4.2,4.8,4.0
15,2015,Stadelhofen,4.6,3.8,4.3,4.4,4.3,4.8,4.1
16,2015,Uster,4.6,4.2,4.3,4.1,4.5,4.9,3.8
17,2015,im Lee,5.1,4.2,4.7,4.5,4.4,4.7,3.9
18,2015,Enge,4.5,3.8,4.2,4.3,4.3,4.6,4.0
19,2015,Kuesnacht,5.1,3.8,5.0,4.5,4.6,5.3,4.3